import { PrismaClient } from "@/lib/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import "dotenv/config";

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL,
});

const prisma = new PrismaClient({
  adapter,
});

const main = async () => {
  const books = [
    {
      title: "The Great Gatsby",
      author: "F. Scott Fitzgerald",
      isbn: "9780743273565",
      publishedYear: 1925,
      price: 15.99,
      genre: "Classic Fiction",
      description: "A classic American novel set in the Jazz Age.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
    },
    {
      title: "To Kill a Mockingbird",
      author: "Harper Lee",
      isbn: "9780061120084",
      publishedYear: 1960,
      price: 18.99,
      genre: "Classic Fiction",
      description:
        "A gripping tale of racial injustice and childhood innocence.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780061120084-L.jpg",
    },
    {
      title: "1984",
      author: "George Orwell",
      isbn: "9780451524935",
      publishedYear: 1949,
      price: 16.99,
      genre: "Dystopian Fiction",
      description: "A dystopian social science fiction novel.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
    },
    {
      title: "Pride and Prejudice",
      author: "Jane Austen",
      isbn: "9780141439518",
      publishedYear: 1813,
      price: 14.99,
      genre: "Romance",
      description: "A romantic novel of manners.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
    },
    {
      title: "The Catcher in the Rye",
      author: "J.D. Salinger",
      isbn: "9780316769488",
      publishedYear: 1951,
      price: 17.99,
      genre: "Classic Fiction",
      description: "A story about teenage rebellion and alienation.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780316769488-L.jpg",
    },
    {
      title: "Harry Potter and the Sorcerer's Stone",
      author: "J.K. Rowling",
      isbn: "9780590353427",
      publishedYear: 1997,
      price: 24.99,
      genre: "Fantasy",
      description: "A young wizard discovers his magical heritage.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780590353427-L.jpg",
    },
    {
      title: "The Hobbit",
      author: "J.R.R. Tolkien",
      isbn: "9780547928227",
      publishedYear: 1937,
      price: 19.99,
      genre: "Fantasy",
      description: "A fantasy adventure in Middle-earth.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg",
    },
    {
      title: "The Da Vinci Code",
      author: "Dan Brown",
      isbn: "9780307474278",
      publishedYear: 2003,
      price: 16.99,
      genre: "Mystery Thriller",
      description: "A mystery thriller involving secret societies.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780307474278-L.jpg",
    },
    {
      title: "The Alchemist",
      author: "Paulo Coelho",
      isbn: "9780062315007",
      publishedYear: 1988,
      price: 14.99,
      genre: "Philosophical Fiction",
      description: "A philosophical novel about following your dreams.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg",
    },
    {
      title: "Brave New World",
      author: "Aldous Huxley",
      isbn: "9780060850524",
      publishedYear: 1932,
      price: 15.99,
      genre: "Dystopian Fiction",
      description: "A dystopian novel about a technologically advanced future.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg",
    },
    {
      title: "The Lord of the Rings",
      author: "J.R.R. Tolkien",
      isbn: "9780544003415",
      publishedYear: 1954,
      price: 35.99,
      genre: "Fantasy",
      description: "An epic high fantasy trilogy.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780544003415-L.jpg",
    },
    {
      title: "Animal Farm",
      author: "George Orwell",
      isbn: "9780452284244",
      publishedYear: 1945,
      price: 13.99,
      genre: "Political Satire",
      description: "An allegorical novella about totalitarianism.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780452284244-L.jpg",
    },
    {
      title: "The Chronicles of Narnia",
      author: "C.S. Lewis",
      isbn: "9780066238500",
      publishedYear: 1950,
      price: 28.99,
      genre: "Fantasy",
      description: "A series of fantasy novels for children.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780066238500-L.jpg",
    },
    {
      title: "Jane Eyre",
      author: "Charlotte Brontë",
      isbn: "9780141441146",
      publishedYear: 1847,
      price: 12.99,
      genre: "Gothic Romance",
      description: "A novel about love, morality, and independence.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780141441146-L.jpg",
    },
    {
      title: "Wuthering Heights",
      author: "Emily Brontë",
      isbn: "9780141439556",
      publishedYear: 1847,
      price: 11.99,
      genre: "Gothic Romance",
      description: "A tale of passion and revenge on the Yorkshire moors.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780141439556-L.jpg",
    },
    {
      title: "The Picture of Dorian Gray",
      author: "Oscar Wilde",
      isbn: "9780141439570",
      publishedYear: 1890,
      price: 13.99,
      genre: "Philosophical Fiction",
      description: "A philosophical novel about vanity and moral corruption.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780141439570-L.jpg",
    },
    {
      title: "Moby-Dick",
      author: "Herman Melville",
      isbn: "9780142437247",
      publishedYear: 1851,
      price: 16.99,
      genre: "Adventure",
      description: "The narrative of Captain Ahab's obsessive quest.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780142437247-L.jpg",
    },
    {
      title: "The Odyssey",
      author: "Homer",
      isbn: "9780140268867",
      publishedYear: -800,
      price: 14.99,
      genre: "Epic Poetry",
      description: "An ancient Greek epic poem.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780140268867-L.jpg",
    },
    {
      title: "The Iliad",
      author: "Homer",
      isbn: "9780140275360",
      publishedYear: -750,
      price: 14.99,
      genre: "Epic Poetry",
      description: "An epic poem set during the Trojan War.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780140275360-L.jpg",
    },
    {
      title: "Crime and Punishment",
      author: "Fyodor Dostoevsky",
      isbn: "9780486415871",
      publishedYear: 1866,
      price: 15.99,
      genre: "Psychological Fiction",
      description: "A psychological thriller about guilt and redemption.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780486415871-L.jpg",
    },
    {
      title: "The Brothers Karamazov",
      author: "Fyodor Dostoevsky",
      isbn: "9780374528379",
      publishedYear: 1880,
      price: 18.99,
      genre: "Philosophical Fiction",
      description: "A philosophical novel exploring faith and doubt.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780374528379-L.jpg",
    },
    {
      title: "War and Peace",
      author: "Leo Tolstoy",
      isbn: "9780199232765",
      publishedYear: 1869,
      price: 22.99,
      genre: "Historical Fiction",
      description:
        "An epic novel of Russian society during the Napoleonic era.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780199232765-L.jpg",
    },
    {
      title: "Anna Karenina",
      author: "Leo Tolstoy",
      isbn: "9780143035008",
      publishedYear: 1877,
      price: 17.99,
      genre: "Classic Fiction",
      description: "A tragic love story set in Russian high society.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780143035008-L.jpg",
    },
    {
      title: "The Count of Monte Cristo",
      author: "Alexandre Dumas",
      isbn: "9780140449266",
      publishedYear: 1844,
      price: 19.99,
      genre: "Adventure",
      description: "An adventure novel about betrayal and revenge.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780140449266-L.jpg",
    },
    {
      title: "Les Misérables",
      author: "Victor Hugo",
      isbn: "9780451419439",
      publishedYear: 1862,
      price: 20.99,
      genre: "Historical Fiction",
      description:
        "A novel about justice, love, and redemption in 19th century France.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780451419439-L.jpg",
    },
    {
      title: "The Three Musketeers",
      author: "Alexandre Dumas",
      isbn: "9780199537259",
      publishedYear: 1844,
      price: 14.99,
      genre: "Adventure",
      description: "A historical adventure novel.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780199537259-L.jpg",
    },
    {
      title: "Frankenstein",
      author: "Mary Shelley",
      isbn: "9780486282114",
      publishedYear: 1818,
      price: 11.99,
      genre: "Gothic Horror",
      description: "A Gothic novel about creation and responsibility.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780486282114-L.jpg",
    },
    {
      title: "Dracula",
      author: "Bram Stoker",
      isbn: "9780486411095",
      publishedYear: 1897,
      price: 12.99,
      genre: "Gothic Horror",
      description: "A Gothic horror novel about the vampire Count Dracula.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780486411095-L.jpg",
    },
    {
      title: "The Scarlet Letter",
      author: "Nathaniel Hawthorne",
      isbn: "9780142437261",
      publishedYear: 1850,
      price: 13.99,
      genre: "Historical Fiction",
      description:
        "A novel about sin, guilt, and redemption in Puritan America.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780142437261-L.jpg",
    },
    {
      title: "The Adventures of Huckleberry Finn",
      author: "Mark Twain",
      isbn: "9780486280615",
      publishedYear: 1884,
      price: 11.99,
      genre: "Adventure",
      description:
        "A novel about friendship and freedom on the Mississippi River.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780486280615-L.jpg",
    },
    {
      title: "The Adventures of Tom Sawyer",
      author: "Mark Twain",
      isbn: "9780486400778",
      publishedYear: 1876,
      price: 10.99,
      genre: "Adventure",
      description:
        "A story about a mischievous boy growing up along the Mississippi.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780486400778-L.jpg",
    },
    {
      title: "Treasure Island",
      author: "Robert Louis Stevenson",
      isbn: "9780486275598",
      publishedYear: 1883,
      price: 11.99,
      genre: "Adventure",
      description: "An adventure novel about pirates and buried treasure.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780486275598-L.jpg",
    },
    {
      title: "The Strange Case of Dr Jekyll and Mr Hyde",
      author: "Robert Louis Stevenson",
      isbn: "9780486266886",
      publishedYear: 1886,
      price: 9.99,
      genre: "Gothic Horror",
      description: "A novella about the duality of human nature.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780486266886-L.jpg",
    },
    {
      title: "Heart of Darkness",
      author: "Joseph Conrad",
      isbn: "9780486264646",
      publishedYear: 1899,
      price: 10.99,
      genre: "Classic Fiction",
      description: "A novella about a journey into the Congo.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780486264646-L.jpg",
    },
    {
      title: "The Great Expectations",
      author: "Charles Dickens",
      isbn: "9780141439563",
      publishedYear: 1861,
      price: 14.99,
      genre: "Classic Fiction",
      description:
        "A novel about the growth and personal development of an orphan.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780141439563-L.jpg",
    },
    {
      title: "A Tale of Two Cities",
      author: "Charles Dickens",
      isbn: "9780486406510",
      publishedYear: 1859,
      price: 13.99,
      genre: "Historical Fiction",
      description: "A historical novel set during the French Revolution.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780486406510-L.jpg",
    },
    {
      title: "Oliver Twist",
      author: "Charles Dickens",
      isbn: "9780141439747",
      publishedYear: 1838,
      price: 12.99,
      genre: "Classic Fiction",
      description: "A novel about a young orphan in Victorian London.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780141439747-L.jpg",
    },
    {
      title: "David Copperfield",
      author: "Charles Dickens",
      isbn: "9780140439441",
      publishedYear: 1850,
      price: 15.99,
      genre: "Classic Fiction",
      description:
        "A semi-autobiographical novel following a young man's life.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780140439441-L.jpg",
    },
    {
      title: "The Grapes of Wrath",
      author: "John Steinbeck",
      isbn: "9780143039433",
      publishedYear: 1939,
      price: 16.99,
      genre: "Historical Fiction",
      description: "A novel about the Great Depression and migrant workers.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780143039433-L.jpg",
    },
    {
      title: "Of Mice and Men",
      author: "John Steinbeck",
      isbn: "9780140177398",
      publishedYear: 1937,
      price: 13.99,
      genre: "Classic Fiction",
      description:
        "A novella about friendship and dreams during the Great Depression.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780140177398-L.jpg",
    },
    {
      title: "The Old Man and the Sea",
      author: "Ernest Hemingway",
      isbn: "9780684801223",
      publishedYear: 1952,
      price: 14.99,
      genre: "Classic Fiction",
      description: "A short novel about an aging fisherman's struggle.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780684801223-L.jpg",
    },
    {
      title: "For Whom the Bell Tolls",
      author: "Ernest Hemingway",
      isbn: "9780684803357",
      publishedYear: 1940,
      price: 17.99,
      genre: "War Fiction",
      description: "A novel set during the Spanish Civil War.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780684803357-L.jpg",
    },
    {
      title: "A Farewell to Arms",
      author: "Ernest Hemingway",
      isbn: "9780684801469",
      publishedYear: 1929,
      price: 16.99,
      genre: "War Fiction",
      description: "A novel about love and war during World War I.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780684801469-L.jpg",
    },
    {
      title: "The Sun Also Rises",
      author: "Ernest Hemingway",
      isbn: "9780743297332",
      publishedYear: 1926,
      price: 15.99,
      genre: "Classic Fiction",
      description: "A novel about expatriates in post-World War I Europe.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780743297332-L.jpg",
    },
    {
      title: "Catch-22",
      author: "Joseph Heller",
      isbn: "9781451626650",
      publishedYear: 1961,
      price: 16.99,
      genre: "War Fiction",
      description: "A satirical novel about World War II.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9781451626650-L.jpg",
    },
    {
      title: "Slaughterhouse-Five",
      author: "Kurt Vonnegut",
      isbn: "9780385333849",
      publishedYear: 1969,
      price: 15.99,
      genre: "Science Fiction",
      description: "A science fiction infused anti-war novel.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780385333849-L.jpg",
    },
    {
      title: "The Bell Jar",
      author: "Sylvia Plath",
      isbn: "9780061148514",
      publishedYear: 1963,
      price: 14.99,
      genre: "Psychological Fiction",
      description: "A semi-autobiographical novel about mental illness.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780061148514-L.jpg",
    },
    {
      title: "One Hundred Years of Solitude",
      author: "Gabriel García Márquez",
      isbn: "9780060883287",
      publishedYear: 1967,
      price: 17.99,
      genre: "Magical Realism",
      description: "A landmark of magical realism.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780060883287-L.jpg",
    },
    {
      title: "Love in the Time of Cholera",
      author: "Gabriel García Márquez",
      isbn: "9780307389732",
      publishedYear: 1985,
      price: 16.99,
      genre: "Magical Realism",
      description: "A love story spanning over fifty years.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780307389732-L.jpg",
    },
    {
      title: "The Handmaid's Tale",
      author: "Margaret Atwood",
      isbn: "9780385490818",
      publishedYear: 1985,
      price: 15.99,
      genre: "Dystopian Fiction",
      description: "A dystopian novel about a totalitarian society.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780385490818-L.jpg",
    },
    {
      title: "Beloved",
      author: "Toni Morrison",
      isbn: "9781400033416",
      publishedYear: 1987,
      price: 16.99,
      genre: "Historical Fiction",
      description: "A novel about the aftermath of slavery.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9781400033416-L.jpg",
    },
    {
      title: "The Kite Runner",
      author: "Khaled Hosseini",
      isbn: "9781594631931",
      publishedYear: 2003,
      price: 16.99,
      genre: "Historical Fiction",
      description: "A story of friendship and redemption set in Afghanistan.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9781594631931-L.jpg",
    },
    {
      title: "A Thousand Splendid Suns",
      author: "Khaled Hosseini",
      isbn: "9781594489501",
      publishedYear: 2007,
      price: 17.99,
      genre: "Historical Fiction",
      description: "A tale of two Afghan women and their enduring bond.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9781594489501-L.jpg",
    },
    {
      title: "The Book Thief",
      author: "Markus Zusak",
      isbn: "9780375842207",
      publishedYear: 2005,
      price: 16.99,
      genre: "Historical Fiction",
      description: "A novel about a girl living in Nazi Germany.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780375842207-L.jpg",
    },
    {
      title: "Life of Pi",
      author: "Yann Martel",
      isbn: "9780156027328",
      publishedYear: 2001,
      price: 15.99,
      genre: "Adventure",
      description:
        "A survival story about a boy stranded on a lifeboat with a tiger.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780156027328-L.jpg",
    },
    {
      title: "The Road",
      author: "Cormac McCarthy",
      isbn: "9780307387899",
      publishedYear: 2006,
      price: 16.99,
      genre: "Post-Apocalyptic Fiction",
      description: "A post-apocalyptic novel about a father and son's journey.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9780307387899-L.jpg",
    },
    {
      title: "All the Light We Cannot See",
      author: "Anthony Doerr",
      isbn: "9781476746586",
      publishedYear: 2014,
      price: 17.99,
      genre: "Historical Fiction",
      description:
        "A novel about a blind French girl and a German boy during World War II.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9781476746586-L.jpg",
    },
  ];

  for (const book of books) {
    const createdBook = await prisma.book.create({
      data: book,
    });
    console.log(`Created book with id: ${createdBook.id}`);
  }

  console.log("Seeding finished.");
};

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
